# -*- coding: utf-8 -*-
"""langchain_config.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1meeqKgYIquqh1LCjkhO5ecn_JBMC1A4J
"""

from warnings import filterwarnings
filterwarnings("ignore")

!pip install langchain openai streamlit newsapi-python

# Storing my API_KEY
import os

os.environ["OPENAI_API_KEY"] = "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"
os.environ["NEWSAPI_KEY"] = "a91d6b1b79f34865adafc0d40bcad9c0"

print("OpenAI API Key:", os.getenv("OPENAI_API_KEY"))
print("NewsAPI Key:", os.getenv("NEWSAPI_KEY"))

!pip install langchain-community

!pip install pyngrok streamlit

!pip install --upgrade pyngrok

from pyngrok import ngrok

# Kill any existing tunnels (prevents port conflicts)
!pkill streamlit

# Replace with your actual ngrok auth token
ngrok.set_auth_token("2sZWsgguMYWTbb80pGz6uP8wcUW_2q6gBAsf9LFLKuUCxeDeZ")

# Set up the Streamlit app to be publicly accessible via ngrok
# Use 'addr' instead of 'port' to specify the address and port
public_url = ngrok.connect(addr="8501")
print(f"Streamlit app is live at: {public_url}")

!pip install newsapi-python

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# langchain
# openai
# streamlit
# newsapi-python
# langchain-community
# pyngrok
#

# Commented out IPython magic to ensure Python compatibility.
# #  LangChain Configuration
# %%writefile langchain_config.py
# from langchain.llms import OpenAI
# from langchain.chains import LLMChain
# from langchain.prompts import PromptTemplate
# from newsapi import NewsApiClient
# import os
# 
# # Load API keys from environment variables
# openai_api_key = os.getenv("OPENAI_API_KEY")
# newsapi_key = os.getenv("NEWSAPI_KEY")  # Assuming you have set this environment variable
# 
# # Initialize OpenAI LLM
# openai_llm = OpenAI(openai_api_key=openai_api_key)
# 
# # Initialize NewsAPI client
# newsapi = NewsApiClient(api_key=newsapi_key)
# 
# # Function to fetch news articles
# def get_news_articles(query):
#     articles = newsapi.get_everything(q=query, language='en', sort_by='relevancy')
#     return articles['articles']
# 
# # Function to summarize articles
# def summarize_articles(articles):
#     summaries = [article['description'] for article in articles if article['description']]
#     return ' '.join(summaries)
# 
# # Function to get overall summary
# def get_summary(query):
#     articles = get_news_articles(query)
#     summary = summarize_articles(articles)
#     return summary
# 
# # Define your prompt template
# template = """
# You are an AI assistant helping an equity research analyst. Given
# the following query, summarize the most relevant news articles.
# Query: {query}
# """
# 
# # Create the prompt and LangChain chain
# prompt = PromptTemplate(template=template, input_variables=['query'])
# llm_chain = LLMChain(prompt=prompt, llm=openai_llm)
#

# Commented out IPython magic to ensure Python compatibility.
# # Building Streamlit Interface
# %%writefile app.py
# import streamlit as st
# import time
# from langchain_config import llm_chain, get_summary  # Import the updated LangChain setup
# 
# # Set page layout
# st.set_page_config(page_title="Equity Research News", layout="wide")
# 
# # Apply custom background color using Streamlit's main container
# st.markdown(
#     """
#     <style>
#     .stApp {
#         background-color: #f0f2f6;  /* Light grey background */
#     }
#     </style>
#     """,
#     unsafe_allow_html=True
# )
# 
# 
# # Header
# st.title("📈 Equity Research News Tool")
# st.write("Enter a stock, industry, or market-related query to get the latest summarized news.")
# 
# # Layout with two columns
# col1, col2 = st.columns([2, 1])
# 
# with col1:
#     query = st.text_input("🔍 Enter your query:", placeholder="e.g., Tesla stock performance")
# 
# with col2:
#     st.info("💡 Example queries:\n- Latest news on Apple stock\n- Banking sector trends\n- Interest rate impact on markets")
# 
# # Button to trigger news retrieval
# if st.button("Get News"):
#     if query:
#         with st.spinner("Fetching latest news... Please wait."):
#             time.sleep(2)  # Simulating delay
#             try:
#                 news_summary = get_summary(query)  # Fetch summarized news
#                 response = llm_chain.invoke({'query': query, 'summaries': news_summary})  # Get LLM response
# 
#                 st.subheader("📌 Summary:")
#                 st.markdown(f"> {response}")  # Use Markdown for better readability
# 
#             except Exception as e:
#                 st.error(f"❌ Error fetching news: {e}")
# 
#     else:
#         st.warning("⚠️ Please enter a query.")
# 
# # Expander for additional information
# with st.expander("📜 About This Tool"):
#     st.write("This tool uses **LangChain** and **OpenAI** to fetch and summarize the latest financial news.")
#

# Run our stramlit app
!nohup streamlit run app.py &